nname: CI/CD Workflow

on:
  push:
    branches:
      - main
      - '*'  # Запускается для всех веток
    tags:
      - 'v*'  # Запускается при добавлении тегов, начинающихся с 'v'
  pull_request:
    branches:
      - main
      - '*'  # Запускается для всех пулл-реквестов, направленных на main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.22'  # Укажите версию Go, которую вы используете

      - name: Install dependencies
        run: go mod tidy

      - name: Run tests
        run: go test ./...  # Запуск всех тестов

  publish:
    runs-on: ubuntu-latest
    needs: test  # Ждем завершения job test

    if: startsWith(github.ref, 'refs/tags/v')  

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to DockerHub
        run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

      - name: Build Docker image
        run: |
          docker build -t myapp_container/hikzzzz:${{ github.ref }} .

      - name: Push Docker image
        run: |
          docker push myapp_container/hikzzzz:${{ github.ref }} 